@startuml class diagram

class App << (C,yellow) Container>> {
    ==state==
    ~isSubmitted
    ~formValues
    ==methods==
    +handleSubmit()

}

class Header << (C,green) Component>> {
    ヘッダー
    ==inner-component==
    <Link>:/
    <Link>:/opinion-form
}
class Footer << (C,green) Component>> {
    フッター
}
class Home << (C,green) Component>> {
    Homeページ
    ==URL==
    /
}


class OpinionForm << (C,green) Component>> {
    ご意見フォームページ
    ==URL==
    /opinion-form
    ==state==
    ~RHF-methods:useForm
    ==props==
    #onSubmit()
    ==methods==
    +onFormSubmit()
    ==inner-component==
    <Prompt>:ページ遷移前に警告
}


class SubmitIndicator << (C,green) Component>> {
    送信完了表示ページ
    ==URL==
    /result
    ==props==
    #setIsSubmitted
    #formValues
    ==methods==
    +onClickDownLoad()
    +createTextForAccepttedContent()
    +createTextBlob()
    +parseGender()
}

App o-- Header
App o-- Footer
App o-- Home
App o-- OpinionForm
App o-- SubmitIndicator

@enduml