@startuml class diagram

class App << (C,yellow) Container>> {
    ==state==
    ~isShowModal
    ~formValues
    ~activeElemStocked
    ==methods==
    +onSubmit()
    +onCloseModal()

}

class OpinionForm << (C,green) Component>> {
    ご意見フォーム
    ==state==
    ~methods:useForm
    ==props==
    #onSubmit()
    ==methods==
    +onSubmit()
}

class Modalizer << (C,lightblue) Higher-Order Component>> {
    子要素をモーダル化
    ==props==
    #modalContainer
    #children
    ==return==
    +createPortal()
}

class SubmitIndicator << (C,green) Component>> {
    送信完了表示ポップアップ
    ==props==
    #formValues
    #onCloseModal
    ==methods==
    +onClickClose()
    +onClickDownLoad()
    +createTextForAccepttedContent()
    +createTextBlob()
}

App o-- OpinionForm
App o-- Modalizer
Modalizer -- SubmitIndicator

@enduml